<?php

namespace NorberFilms\Bundle\AdminBundle\Repository;

/**
 * enlaces_comprasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enlaces_comprasRepository extends \Doctrine\ORM\EntityRepository
{
}
