<?php

namespace NorberFilms\Bundle\AdminBundle\Repository;

/**
 * redes_socialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class redes_socialesRepository extends \Doctrine\ORM\EntityRepository
{
}
