<?php

namespace NorberFilms\Bundle\AdminBundle\Repository;

/**
 * trabajan_enRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trabajan_enRepository extends \Doctrine\ORM\EntityRepository
{
}
