<?php

namespace NorberFilms\Bundle\AdminBundle\Repository;

/**
 * videosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videosRepository extends \Doctrine\ORM\EntityRepository
{
}
